export const formInicial = {
  nombre: "", periodo: "escolar", categoria: "", grupo: "", horario: "",
  grupoEtario: "",
  gradosAplicables: [], edadMinima: "", edadMaxima: "", fechaNacimientoDesde: "", fechaNacimientoHasta: "", dias: [], horaInicio: "", horaFin: "",
  almuerzoInicio: "", almuerzoFin: "",
  horariosPorGrupo: [], usaHorariosPorBloque: false, talleresDeportivos: [],
  fechaInicio: "", fechaFin: "", duracionAvisoDias: "7", horaLimiteAviso: "23:59", cupos: "", costo: "", modalidadCobro: "Unico",
  cicloI: "", cicloII: "",
  responsable: "", tutora: "", plantilla: "", plantillaBase64: "", plantillaVariables: [],
  plantillaValidada: false, plantillaActualizadaEn: "", requisitos: "",
  comunicado: "", comunicadoCompleto: "", detalleCosto: "", detalleAlmuerzo: "", concesionarios: "",
  requiereUniforme: false, requiereIndumentaria: false, invitacionMasiva: false, alcanceInvitacionMasiva: "colegio",
  anuncioImagen: "", anuncioImagenNombre: "", anuncioImagenTamano: 0, anuncioImagenComprimida: false,
  usarFechaLimiteInscripcion: false,
  fechaAperturaInscripcion: "",
  horaAperturaInscripcion: "",
  fechaLimiteInscripcion: "",
  horaLimiteInscripcion: "",

  // Nuevos campos condicionales por tipo de circular
  tipoComunicado: "Otro genérico",
  tipoDocumento: "Comunicado",
  numeroDocumento: "",
  areaTematica: "Matemática",
  nombreCiclo: "Ciclo I",
  tablaHorariosNivel: [],
  incluyeAlmuerzo: false,
  horarioRecepcionAlmuerzo: "",
  nivelCambridge: "",
  modalidadesCambridge: [],
  costoCiclo: "",
  montoPrimerPago: "",

  // Campos específicos para Inscripción Exámenes Internacionales
  fechaExamen: "",
  lugarExamen: "Colegio Matemático San Rafael",
  precioStarters: "315.00",
  precioMovers: "345.00",
  precioFlyers: "360.00",
  precioKet: "475.00",
  precioPet: "490.00",
  numeroCuotas: "3",
  fechaVencCuota1: "",
  fechaVencCuota2: "",
  fechaVencCuota3: "",
  fechaLimitePago: "",
};

export const horarioGrupoInicial = {
  grados: [],
  dia: "Jueves",
  almuerzoInicio: "14:20",
  almuerzoFin: "15:10",
  horaInicio: "15:20",
  horaFin: "17:20",
  aula: "",
  responsable: "",
  tutora: "",
};

export const TEMPLATES_POR_TIPO = {
  "Inscripción Exámenes Internacionales": { comunicado: "", requisitos: "" },
  "Club de Tareas": { comunicado: "", requisitos: "" },
  "Reforzamiento (Circular)": { comunicado: "", requisitos: "" },
  "Certificación Cambridge": { comunicado: "", requisitos: "" },
  "Cambridge": { comunicado: "", requisitos: "" },
  "Selección (Circular)": { comunicado: "", requisitos: "" },
  "Maratón (Circular)": { comunicado: "", requisitos: "" },
  "Otro genérico": { comunicado: "", requisitos: "" }
};
