export const columnasDisponiblesMap = {
  inscripciones: [
    { key: "id", label: "Código de Inscripción" },
    { key: "dni", label: "DNI Estudiante" },
    { key: "estudiante", label: "Nombres Estudiante" },
    { key: "grado", label: "Grado Aplicable" },
    { key: "programa", label: "Programa / Taller" },
    { key: "estadoInscripcion", label: "Estado Inscripción" },
    { key: "estadoPago", label: "Estado de Pago" },
    { key: "costo", label: "Costo / Monto" },
    { key: "origen", label: "Canal / Origen" },
    { key: "fechaRegistro", label: "Fecha de Registro" },
    { key: "apoderado", label: "Nombre Apoderado" },
    { key: "telefono", label: "Teléfono Apoderado" },
  ],
  programas: [
    { key: "id", label: "Código de Taller" },
    { key: "nombre", label: "Taller / Programa" },
    { key: "periodo", label: "Periodo / Ciclo" },
    { key: "estado", label: "Estado Taller" },
    { key: "categoria", label: "Categoría" },
    { key: "responsable", label: "Profesor Responsable" },
    { key: "inscritos", label: "Total Alumnos" },
    { key: "conBeca", label: "Alumnos con Beca" },
    { key: "cupos", label: "Cupos Totales" },
    { key: "avance", label: "Porcentaje Ocupación (%)" },
    { key: "costo", label: "Precio Lista (S/)" },
    { key: "proyectado", label: "Total Esperado (S/)" },
    { key: "recaudado", label: "Monto Recaudado (S/)" },
    { key: "porCobrar", label: "Por Cobrar (S/)" },
  ],
  pagos: [
    { key: "id", label: "Código Transacción" },
    { key: "dni", label: "DNI Estudiante" },
    { key: "estudiante", label: "Nombre Estudiante" },
    { key: "programa", label: "Programa / Taller" },
    { key: "beca", label: "Beca" },
    { key: "descuento", label: "Descuento" },
    { key: "anulado", label: "Anulado" },
    { key: "estadoFinanciero", label: "Estado Pago" },
    { key: "montoPagado", label: "Monto Pagado" },
    { key: "montoAnulado", label: "Monto Anulado" },
    { key: "medio", label: "Medio de Pago" },
    { key: "fecha", label: "Fecha Pago" },
    { key: "nroRecibo", label: "N° de comprobante" },
    { key: "observaciones", label: "Observaciones / Motivo Anulación" },
  ],
  direccion_alumnos_pagos: [
    { key: "index", label: "N°" },
    { key: "estudiante", label: "Nombres y Apellidos" },
    { key: "grado", label: "Grado" },
    { key: "seccion", label: "Sección" },
    { key: "fechaPago", label: "Fecha Pago" },
    { key: "nroRecibo", label: "N° de comprobante" },
    { key: "beca", label: "Beca" },
    { key: "descuento", label: "Descuento" },
    { key: "anulado", label: "Anulado" },
    { key: "estadoFinanciero", label: "Estado Pago" },
    { key: "montoPagado", label: "Monto Pagado" },
    { key: "montoAnulado", label: "Monto Anulado" },
    { key: "dni", label: "DNI Estudiante" },
    { key: "apoderado", label: "Nombre Apoderado" },
    { key: "telefono", label: "Teléfono Apoderado" },
    { key: "programa", label: "Programa / Taller" },
    { key: "costoOriginal", label: "Precio Lista (S/)" },
    { key: "descuentoAprobado", label: "¿Tiene Beca/Descuento?" },
    { key: "descuentoTipo", label: "Tipo Descuento" },
    { key: "descuentoValor", label: "Valor Descuento" },
    { key: "descuentoMonto", label: "Monto Descuento (S/)" },
    { key: "costo", label: "Costo / Pago" },
    { key: "pendiente", label: "Monto Pendiente" },
    { key: "estadoPago", label: "Estado de Pago" },
    { key: "medioPago", label: "Medio de Pago" },
    { key: "nroOperacion", label: "N° Operación" },
    { key: "origen", label: "Canal / Origen" },
    { key: "fechaRegistro", label: "Fecha Registro" },
    { key: "observaciones", label: "Observaciones / Motivo Anulación" },
  ],
  direccion_alumnos_asistencias: [
    { key: "index", label: "N°" },
    { key: "estudiante", label: "Nombres y Apellidos" },
    { key: "grado", label: "Grado" },
    { key: "seccion", label: "Sección" },
    { key: "dni", label: "DNI Estudiante" },
    { key: "programa", label: "Programa / Taller" },
    { key: "telefono", label: "Teléfono Apoderado" },
  ],
};

export const opcionesReportesSimplificados = [
  { value: "direccion_alumnos_pagos", label: "Consolidado de Alumnos, Pagos y Becas" },
  { value: "direccion_alumnos_asistencias", label: "Consolidado de Alumnos y Asistencias (Asistió ✓ / Faltó —)" },
  { value: "programas_catalogo", label: "Resumen General por Taller" },
];
