import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BACKUP_PATH = path.join(__dirname, 'supabase_backup.json');
const SQL_PATH = path.join(__dirname, 'schema.sql');

const COLUMNS_DEF = {
  usuarios: ["id", "nombre", "usuario", "rol", "estado", "contrasena"],
  estudiantes: ["dni", "codigoEstudiante", "nombres", "grado", "seccion", "nivel", "sexo", "fechaNacimiento", "tipoAlumno", "estadoMatricula", "apoderado", "telefonoApoderado", "correoApoderado", "estadoInscripcion", "estadoCaja"],
  estudiantes_externos: ["dni", "codigoEstudiante", "nombres", "grado", "seccion", "nivel", "sexo", "fechaNacimiento", "tipoAlumno", "estadoMatricula", "apoderado", "telefonoApoderado", "correoApoderado", "estadoInscripcion", "estadoCaja"],
  programas: ["id", "nombre", "categoria", "fechaInicio", "fechaFin", "costo", "cupos", "cuposOcupados", "gradosAplicables", "periodo", "modalidadCobro", "horario", "grupo"],
  programas_configuraciones: ["programaId", "duracionAvisoDias", "horaLimiteAviso", "edadMinima", "edadMaxima", "grupoEtario", "requisitos", "comunicado", "comunicadoCompleto", "detalleCosto", "creadoDesdeDocumento", "duracionTaller", "invitacionMasiva", "alcanceInvitacionMasiva", "tipoComunicado", "motivoJustificacion", "duracion", "docente", "responsable", "estado"],
  programas_horarios: ["programaId", "horaInicio", "horaFin", "horariosPorGrupo", "tablaHorariosNivel"],
  programas_servicios: ["programaId", "requiereUniforme", "requiereIndumentaria", "talleresDeportivos", "incluyeAlmuerzo", "horarioRecepcionAlmuerzo", "concesionarios", "detalleAlmuerzo", "nivelCambridge", "modalidadesCambridge", "costoCiclo", "montoPrimerPago", "cicloI", "cicloII", "nombreCiclo"],
  programas_documentos: ["programaId", "plantilla", "plantillaBase64", "plantillaVariables", "plantillaValidada", "tipoDocumento", "numeroDocumento", "areaTematica"],
  programas_anuncios: ["programaId", "anuncioImagen", "anuncioImagenNombre", "anuncioImagenTamano", "anuncioImagenComprimida"],
  inscripciones: [
    "id", "dniEstudiante", "codigoEstudiante", "nombresEstudiante", "gradoEstudiante", "seccion",
    "programaId", "programa", "categoria", "periodo", "horario", "docente", "costo",
    "modalidadCobro", "fechaInicio", "fechaFin", "estadoPago", "pagoId",
    "costoOriginal", "descuentoAprobado", "descuentoTipo", "descuentoValor", "descuentoMonto",
    "descuentoJustificacion", "descuentoAprobadoPor", "descuentoFechaAprobacion",
    "derivadoCaja", "estadoCaja", "origenRegistro", "fechaRegistro"
  ],
  pagos: ["id", "inscripcionId", "dniEstudiante", "nombresEstudiante", "programaId", "programa", "periodo", "monto", "formaPago", "numeroOperacion", "telefonoOperacion", "capturaPagoNombre", "capturaPagoBase64", "estado", "fechaPago", "origenRegistro", "nro_recibo"],
  asistencias: ["id", "inscripcionId", "pagoId", "dniEstudiante", "codigoEstudiante", "nombresEstudiante", "programaId", "programa", "horario", "estadoPago", "estadoAcceso", "observacion", "origen", "fechaRegistro"],
  invitados_programa: ["programaId", "dni", "nombres", "grado", "seccion", "seleccion", "nivelCambridge"],
  historial_cargas: ["id", "fecha", "periodo", "archivoNombre", "archivos", "usuario", "resumen", "registros"],
  configuracion: ["clave", "valor", "updated_at"],
  categorias: ["id", "categoria"],
  audit_logs: ["id", "usuario", "rol", "fecha", "accion", "detalles"]
};

const PRIMARY_KEYS = {
  usuarios: "id",
  estudiantes: "dni",
  estudiantes_externos: "dni",
  programas: "id",
  programas_configuraciones: "programaId",
  programas_horarios: "programaId",
  programas_servicios: "programaId",
  programas_documentos: "programaId",
  programas_anuncios: "programaId",
  inscripciones: "id",
  pagos: "id",
  asistencias: "id",
  historial_cargas: "id",
  configuracion: "clave",
  categorias: "id",
  audit_logs: "id"
};

// Explicit type overrides for columns where data inspection might be empty or misleading
const TYPE_OVERRIDES = {
  // Integers / Numbers
  "programas.costo": "NUMERIC",
  "programas.cupos": "INTEGER",
  "programas.cuposOcupados": "INTEGER",
  "programas_configuraciones.duracionAvisoDias": "INTEGER",
  "programas_configuraciones.edadMinima": "INTEGER",
  "programas_configuraciones.edadMaxima": "INTEGER",
  "programas_configuraciones.duracionTaller": "INTEGER",
  "programas_configuraciones.duracion": "INTEGER",
  "programas_servicios.costoCiclo": "NUMERIC",
  "programas_servicios.montoPrimerPago": "NUMERIC",
  "programas_anuncios.anuncioImagenTamano": "INTEGER",
  "inscripciones.costo": "NUMERIC",
  "inscripciones.costoOriginal": "NUMERIC",
  "inscripciones.descuentoValor": "NUMERIC",
  "inscripciones.descuentoMonto": "NUMERIC",
  "pagos.monto": "NUMERIC",
  "categorias.id": "BIGINT GENERATED BY DEFAULT AS IDENTITY",

  // Booleans
  "programas_configuraciones.invitacionMasiva": "BOOLEAN",
  "programas_configuraciones.creadoDesdeDocumento": "BOOLEAN",
  "programas_servicios.requiereUniforme": "BOOLEAN",
  "programas_servicios.requiereIndumentaria": "BOOLEAN",
  "programas_servicios.incluyeAlmuerzo": "BOOLEAN",
  "programas_servicios.cicloI": "BOOLEAN",
  "programas_servicios.cicloII": "BOOLEAN",
  "programas_documentos.plantillaValidada": "BOOLEAN",
  "inscripciones.derivadoCaja": "BOOLEAN",

  // JSON / JSONB
  "programas.gradosAplicables": "JSONB",
  "programas_configuraciones.comunicadoCompleto": "JSONB",
  "programas_horarios.horariosPorGrupo": "JSONB",
  "programas_horarios.tablaHorariosNivel": "JSONB",
  "programas_servicios.talleresDeportivos": "JSONB",
  "programas_servicios.concesionarios": "JSONB",
  "programas_servicios.modalidadesCambridge": "JSONB",
  "programas_documentos.plantillaVariables": "JSONB",
  "historial_cargas.archivos": "JSONB",
  "historial_cargas.resumen": "JSONB",
  "historial_cargas.registros": "JSONB",
  "audit_logs.detalles": "JSONB"
};

async function main() {
  const rawData = await fs.readFile(BACKUP_PATH, 'utf8');
  const backup = JSON.parse(rawData);

  let sql = `-- SCRIPT DE CREACIÓN DE ESQUEMA PARA SUPABASE\n`;
  sql += `-- Generado automáticamente para migración de cuenta\n\n`;

  // First drop tables if they exist to start clean (in reverse dependency order)
  const dropOrder = [
    "programas_configuraciones",
    "programas_horarios",
    "programas_servicios",
    "programas_documentos",
    "programas_anuncios",
    "invitados_programa",
    "asistencias",
    "pagos",
    "inscripciones",
    "programas",
    "estudiantes_externos",
    "estudiantes",
    "usuarios",
    "historial_cargas",
    "configuracion",
    "categorias",
    "audit_logs"
  ];

  sql += `-- 0. LIMPIEZA DE TABLAS EXISTENTES\n`;
  for (const table of dropOrder) {
    sql += `DROP TABLE IF EXISTS "${table}" CASCADE;\n`;
  }
  sql += `\n`;

  // Define creation order (parent tables first)
  const createOrder = [
    "usuarios",
    "estudiantes",
    "estudiantes_externos",
    "programas",
    "inscripciones",
    "pagos",
    "asistencias",
    "invitados_programa",
    "historial_cargas",
    "configuracion",
    "categorias",
    "audit_logs",
    "programas_configuraciones",
    "programas_horarios",
    "programas_servicios",
    "programas_documentos",
    "programas_anuncios"
  ];

  for (const table of createOrder) {
    sql += `-- ==========================================\n`;
    sql += `-- TABLA: ${table}\n`;
    sql += `-- ==========================================\n`;
    sql += `CREATE TABLE "${table}" (\n`;

    const columns = COLUMNS_DEF[table];
    const columnDefinitions = [];

    // Check existing records in backup to aid in type inference
    const records = backup[table] || [];

    for (const col of columns) {
      const typeOverrideKey = `${table}.${col}`;
      let colType = "TEXT"; // Default

      if (TYPE_OVERRIDES[typeOverrideKey]) {
        colType = TYPE_OVERRIDES[typeOverrideKey];
      } else {
        // Look at values in backup for type inference
        let foundNonNull = false;
        let isBoolean = false;
        let isNumber = false;
        let isInteger = false;
        let isJson = false;

        for (const rec of records) {
          const val = rec[col];
          if (val !== undefined && val !== null && val !== "") {
            foundNonNull = true;
            if (typeof val === 'boolean') {
              isBoolean = true;
            } else if (typeof val === 'number') {
              isNumber = true;
              if (Number.isInteger(val)) isInteger = true;
            } else if (typeof val === 'object') {
              isJson = true;
            }
            break;
          }
        }

        if (foundNonNull) {
          if (isBoolean) colType = "BOOLEAN";
          else if (isJson) colType = "JSONB";
          else if (isNumber) colType = isInteger ? "INTEGER" : "NUMERIC";
        }
      }

      let colDef = `  "${col}" ${colType}`;

      // Handle primary keys
      if (PRIMARY_KEYS[table] === col) {
        if (!colDef.includes("BIGINT GENERATED BY DEFAULT AS IDENTITY")) {
          colDef += " PRIMARY KEY";
        } else {
          // If it is BIGINT GENERATED, it is already the primary key
          colDef += " PRIMARY KEY";
        }
      }

      columnDefinitions.push(colDef);
    }

    // Add Foreign Key constraints where appropriate
    if (table === "programas_configuraciones" || table === "programas_horarios" || table === "programas_servicios" || table === "programas_documentos" || table === "programas_anuncios") {
      columnDefinitions.push(`  CONSTRAINT fk_programa FOREIGN KEY ("programaId") REFERENCES "programas" ("id") ON DELETE CASCADE`);
    } else if (table === "invitados_programa") {
      columnDefinitions.push(`  CONSTRAINT fk_programa FOREIGN KEY ("programaId") REFERENCES "programas" ("id") ON DELETE CASCADE`);
      columnDefinitions.push(`  PRIMARY KEY ("programaId", "dni")`);
    } else if (table === "inscripciones") {
      columnDefinitions.push(`  CONSTRAINT fk_programa FOREIGN KEY ("programaId") REFERENCES "programas" ("id") ON DELETE CASCADE`);
    } else if (table === "pagos") {
      columnDefinitions.push(`  CONSTRAINT fk_inscripcion FOREIGN KEY ("inscripcionId") REFERENCES "inscripciones" ("id") ON DELETE SET NULL`);
      columnDefinitions.push(`  CONSTRAINT fk_programa FOREIGN KEY ("programaId") REFERENCES "programas" ("id") ON DELETE SET NULL`);
    } else if (table === "asistencias") {
      columnDefinitions.push(`  CONSTRAINT fk_inscripcion FOREIGN KEY ("inscripcionId") REFERENCES "inscripciones" ("id") ON DELETE SET NULL`);
      columnDefinitions.push(`  CONSTRAINT fk_pago FOREIGN KEY ("pagoId") REFERENCES "pagos" ("id") ON DELETE SET NULL`);
      columnDefinitions.push(`  CONSTRAINT fk_programa FOREIGN KEY ("programaId") REFERENCES "programas" ("id") ON DELETE CASCADE`);
    }

    sql += columnDefinitions.join(",\n");
    sql += `\n);\n\n`;
  }

  // Create RLS disable statements since this client-side API does direct operations and might bypass RLS or needs RLS disabled
  sql += `-- HABILITAR ACCESO COMPLETO (DESACTIVAR RLS PARA SIMPLIFICAR EL MÓDULO ACTUAL)\n`;
  for (const table of createOrder) {
    sql += `ALTER TABLE "${table}" DISABLE ROW LEVEL SECURITY;\n`;
  }
  sql += `\n`;

  // Grant privileges to anon and authenticated roles
  sql += `-- CONCEDER PERMISOS A LOS ROLES ANON Y AUTHENTICATED\n`;
  for (const table of createOrder) {
    sql += `GRANT ALL PRIVILEGES ON TABLE "${table}" TO anon, authenticated, service_role;\n`;
  }
  sql += `GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;\n`;

  await fs.writeFile(SQL_PATH, sql, "utf8");
  console.log(`✅ Esquema SQL generado con éxito en: ${SQL_PATH}`);
}

main();
