@startuml
skinparam handwritten false
skinparam monochrome false
skinparam shadowing true
skinparam packageStyle rect
skinparam defaultFontName "Calibri"

title Diagrama 1: Arquitectura de Despliegue Físico y Topología

node "Dispositivo Cliente (PC, Laptop, Smartphone)" as client_pc {
    component [Web Browser (Chrome/Safari)] as browser
}

node "Servidor Web / DNS (Cloud/Vercel/Nginx)" as web_srv {
    component [Static Assets (HTML/JS/CSS)] as static_fe
}

node "Servidor de Aplicación (Node.js VPS corriendo con PM2)" as app_srv {
    component [Express REST API (dist/app.js)] as backend_app
    component [Sequelize ORM] as sequelize
    backend_app --> sequelize
}

node "Servidor de Base de Datos (PostgreSQL)" as db_srv {
    database "extracurricular (DB)" as db
}

node "Servidor de Correo (SMTP Relay)" as mail_srv {
    component [Nodemailer Client] as smtp
}

browser --> static_fe : 1. Descarga frontend (HTTPS)
browser --> backend_app : 2. Peticiones API REST (JSON + JWT)
sequelize --> db : 3. Consultas SQL Seguras (SSL: true)
backend_app --> smtp : 4. Envío de Notificaciones (Email)

@endum
